AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-ec2-server-manager

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs16.x

Resources:
  BotRequestHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/
      Handler: app.default
      Layers:
        - !Ref NodeModulesDependencyLayer
      Architectures:
        - x86_64
      Events:
        BotRequestHandler:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bot
            Method: get
  NodeModulesDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nodejs-dependencies
      Description: Node Modules
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs16.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DiscordEC2ServerManagerApi:
    Description: "API Gateway endpoint URL for Prod stage for Bot Request Handler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BotRequestHandlerFunction:
    Description: "Bot Request Handler Lambda Function ARN"
    Value: !GetAtt BotRequestHandlerFunction.Arn
  BotRequestHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Bot Request Handler function"
    Value: !GetAtt BotRequestHandlerFunctionRole.Arn
